columnSuffix: null
handle: href
instructions: null
name: Link
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: language
type: craft\fields\Link
