columnSuffix: null
handle: limitedText
instructions: null
name: 'Limited Text'
searchable: false
settings:
  byteLimit: null
  charLimit: 160
  code: false
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
