columnSuffix: null
handle: sectionSelector
instructions: 'Select a section that will be shown.'
name: 'Section Selector'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - News
        -
          - value
          - news
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Projects
        -
          - value
          - projects
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - People
        -
          - value
          - people
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
