defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2431e82f-e2e9-4324-a927-dbfc08d11ee3 # Landing Page
handle: aboutPage
maxAuthors: 1
name: 'About Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  457fe23e-c489-407c-acdb-7141642fc34c: # Studio Clean EN
    enabledByDefault: true
    hasUrls: true
    template: _layouts/_landing.twig
    uriFormat: '{slug}'
  cb9af26b-9d97-4e88-8dfc-ae91f5841903: # Studio Clean
    enabledByDefault: true
    hasUrls: true
    template: _layouts/_landing.twig
    uriFormat: '{slug}'
type: single
