defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2e95471e-21e6-4477-b1fe-39bdae9a8ce3 # Dynamic Page
handle: dynamicPage
maxAuthors: 1
name: 'Dynamic Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  457fe23e-c489-407c-acdb-7141642fc34c: # Studio Clean EN
    enabledByDefault: true
    hasUrls: true
    template: dynamic-page/_entry.twig
    uriFormat: '{slug}'
  cb9af26b-9d97-4e88-8dfc-ae91f5841903: # Studio Clean
    enabledByDefault: true
    hasUrls: true
    template: dynamic-page/_entry.twig
    uriFormat: '{slug}'
type: channel
