defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c7a0f081-3599-4faa-a0e8-81d26c233ea6 # Detail Page
handle: projects
maxAuthors: 1
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  457fe23e-c489-407c-acdb-7141642fc34c: # Studio Clean EN
    enabledByDefault: true
    hasUrls: true
    template: detail.twig
    uriFormat: 'projects/{slug}'
  cb9af26b-9d97-4e88-8dfc-ae91f5841903: # Studio Clean
    enabledByDefault: true
    hasUrls: true
    template: detail.twig
    uriFormat: 'projecten/{slug}'
structure:
  maxLevels: 1
  uid: 6cf8d67d-861c-4cba-a2b6-da9de0724d4a
type: structure
