altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  caab8524-e9c4-4917-83a5-0deeb7c13611:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-27T08:44:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1b053184-77aa-465b-a141-8fd809d909a3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bd10797e-4efd-45c5-8699-e5abf5b6b42e
        userCondition: null
fs: pdf
handle: pdf
name: PDF
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: none
transformFs: ''
transformSubpath: ''
