color: orange
fieldLayouts:
  cb629d7f-dda5-45c4-a85d-51063f149ff9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-27T10:44:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4eebb68c-b41c-46af-be73-254bacbba2ff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T10:46:01+00:00'
            elementCondition: null
            fieldUid: 55b1b17b-3a3a-4e74-a5a6-8e16a1d1e3d5 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 953c5120-5b2b-423b-8a56-b44590f02ff9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cfaae566-8972-4113-be86-3954b34f7fe3
        userCondition: null
handle: bannerBlock
hasTitleField: true
icon: panorama
name: 'Banner Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
