color: orange
fieldLayouts:
  8bb5d2e6-fd3c-4a91-9c64-36311dae5eb7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-27T10:42:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 53122c97-be05-46e3-b8f4-0a1fd74125cd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T11:04:30+00:00'
            elementCondition: null
            fieldUid: 2aac35a5-989c-42bc-897c-db0a9c777ccc # Section Selector
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5a2d079-3800-4cd1-9e8e-f25b9e548ea6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T10:43:45+00:00'
            elementCondition: null
            fieldUid: 60948141-e7aa-4691-98b5-d6a41822b018 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cc37213-c557-4665-8f80-06212e2fc631
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 330ebb73-c9d8-4dea-893d-d3f6bd9f96c8
        userCondition: null
handle: cardsBlock
hasTitleField: true
icon: diamond
name: 'Cards Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
