color: cyan
fieldLayouts:
  a4f206ca-2a24-4a06-90b9-9e6a83662f83:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-27T10:36:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e78fdbe0-7ba7-4011-a534-218b4adde5c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T10:55:57+00:00'
            elementCondition: null
            fieldUid: 7833fd76-bf03-48fb-b050-9ef2bb60de3b # Simple Text
            handle: null
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a1775fc-170c-443e-80e3-f911730f46cd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T10:38:01+00:00'
            elementCondition: null
            fieldUid: 2aac35a5-989c-42bc-897c-db0a9c777ccc # Section Selector
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e30c7d68-97da-44a4-ac44-6cd004ebd9da
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 32ade682-01b4-43bf-b208-bc9ef119e873
        userCondition: null
handle: gridPage
hasTitleField: true
icon: grid
name: 'Grid Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
